### ISSUE TITLE
TinyDB has bad performance when data size increase

### ISSUE THREAD

**Issue by jingedawang** [jingedawang/StockPredictor#17]
As we add more and more data to database, it becomes more and more slowly to insert or update.

May need other database with better performance.

**Comment by jingedawang** [comment]
Let's try MongoDB.

**Comment by chenshoval** [comment]
on it !

**Comment by jingedawang** [comment]
We expect changing to MongoDB will speed up the procedures like `load_stock_list` and `predict_all`. It's better to test the execution times before and after the modification.

**Comment by jingedawang** [comment]
Hi @chenshoval , I guess you are busy on other works. It's a long time since you last work on this issue. The code has changed a lot. I would prefer to tackle this issue by myself if you don't mind. 😃
