### ISSUE TITLE
Let's apply a domain name for our website

### ISSUE THREAD

**Issue by jingedawang** [jingedawang/StockPredictor#52]
Using IP address is a little informal. Let's apply a domain name for our website and people would like to use it then.

**Comment by vincilee2** [comment]
It's easy to make a change if you are using azure public ip, you can just type a domain name in the azure public ip management panel.

**Comment by jingedawang** [comment]
Cool, I'll try it!

**Comment by jingedawang** [comment]
Purchase a domain stockprediction.org in App Service Domains in Azure. Then add it to a DNS zone to make it take effect.
We could use http://stockprediction.org from now.
