### ISSUE TITLE
Task 1.2: Let the model predict the price after 2 weeks

### ISSUE THREAD

**Issue by jingedawang** [jingedawang/StockPredictor#6]
Established a code example to support the prediction we want.

Please see this branch for details: https://github.com/jingedawang/StockPredictor/tree/setup/algorithm
There are still some TODOs need to be solved in the code.

**Comment by shawn1906** [comment]
Do we have any criteria for this requirement (e.g. from a statistical perspective, what is the confidence interval/level, how accurate is the prediction, etc.)?  Thanks.

**Comment by jingedawang** [comment]
Thanks for point it out! Yes, we have some criteria to evaluate the model. I explained them in the next task, please see #7 for more details.
